## Introduction
There are 5 general mechanisms for creating arrays:

Conversion from other Python structures (e.g., lists, tuples)

Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions (e.g., random)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [3]:
x = np.array([[1,2],[1,3]])
print(x)

[[1 2]
 [1 3]]


In [4]:
x = np.array([[1,2],[1,3,4],[1,3,4]])
print(x)

[list([1, 2]) list([1, 3, 4]) list([1, 3, 4])]


In [5]:
x = np.array([[1.3,2],[1.,3.14,4],(1,3.54,4)])
print(x)

[list([1.3, 2]) list([1.0, 3.14, 4]) (1, 3.54, 4)]


### Intrinsic NumPy Array Creation
NumPy has built-in functions for creating arrays from scratch:

#### zeros
zeros(shape) will create an array filled with 0 values with the specified shape. The default dtype is float64.

In [6]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [7]:
z = np.zeros((3,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
z = np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


#### ones
ones(shape) will create an array filled with 1 values. It is identical to zeros in all other respects.

In [11]:
o = np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


In [17]:
o = np.ones((5,2))
print(o)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### arange
arange() will create arrays with regularly incrementing values. Check the docstring for complete information on the various ways it can be used. A few examples will be given here:

In [19]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [20]:
a = np.arange(3,6)
print(a)

[3 4 5]


In [22]:
a = np.arange(3,10,2)
print(a)

[3.  5.5 8. ]


In [23]:
a = np.arange(1,10, 0.75)
print(a)

[1.   1.75 2.5  3.25 4.   4.75 5.5  6.25 7.   7.75 8.5  9.25]


In [26]:
a = np.arange(3,6, dtype=float)
print(a)

[3. 4. 5.]


#### linspace
linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

In [27]:
l = np.linspace(0,1,5)
print(l)

[0.   0.25 0.5  0.75 1.  ]


In [28]:
l = np.linspace(0,1,15)
print(l)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


In [30]:
l = np.linspace(5, 10, 7)
print(l)

[ 5.          5.83333333  6.66666667  7.5         8.33333333  9.16666667
 10.        ]


In [42]:
ls = np.logspace(1.,2.,num=10)
print(ls)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [41]:
ls = np.logspace(2.0, 3.0, 5)
print(ls)

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]
