In [1]:
# Python program for
# Creation of Arrays
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [10]:
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print (arr)

# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)


[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [14]:
print (arr)

# Printing type of arr object 
print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (4, 4)
Size of array:  16
Array stores elements of type:  float64


In [15]:
Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer interface, optional
    Used to fill the array with data.
offset : int, optional
    Offset of array data in buffer.
strides : tuple of ints, optional
    Strides of data in memory.
order : {'C', 'F'}, optional
    Row-major (C-style) or column-major (Fortran-style) order.

Attributes
----------
T : ndarray
    Transpose of the array.
data : buffer
    The array's elements, in memory.
dtype : dtype object
    Describes the format of the elements in the array.
flags : dict
    Dictionary containing information related to memory use, e.g.,
    'C_CONTIGUOUS', 'OWNDATA', 'WRITEABLE', etc.
flat : numpy.flatiter object
    Flattened version of the array as an iterator.  The iterator
    allows assignments, e.g., ``x.flat = 3`` (See `ndarray.flat` for
    assignment examples; TODO).
imag : ndarray
    Imaginary part of the array.
real : ndarray
    Real part of the array.
size : int
    Number of elements in the array.
itemsize : int
    The memory use of each array element in bytes.
nbytes : int
    The total number of bytes required to store the array data,
    i.e., ``itemsize * size``.
ndim : int
    The array's number of dimensions.
shape : tuple of ints
    Shape of the array.
strides : tuple of ints
    The step-size required to move from one element to the next in
    memory. For example, a contiguous ``(3, 4)`` array of type
    ``int16`` in C-order has strides ``(8, 2)``.  This implies that
    to move from element to element in memory requires jumps of 2 bytes.
    To move from row-to-row, one needs to jump 8 bytes at a time
    (``2 * 4``).
ctypes : ctypes object
    Class containing properties of the array needed for interaction
    with ctypes.
base : ndarray
    If the array is a view into another array, that array is its `base`
    (unless that array is also a view).  The `base` array is where the
    array data is actually stored.

See Also
--------
array : Construct an array.
zeros : Create an array, each element of which is zero.
empty : Create an array, but leave its allocated memory unchanged (i.e.,
        it contains "garbage").
dtype : Create a data-type.

Notes
-----
There are two modes of creating an array using ``__new__``:

1. If `buffer` is None, then only `shape`, `dtype`, and `order`
   are used.
2. If `buffer` is an object exposing the buffer interface, then
   all keywords are interpreted.

No ``__init__`` method is needed because the array is fully initialized
after the ``__new__`` method.

SyntaxError: invalid syntax (<ipython-input-15-6fbcfbcc4e8b>, line 2)

In [37]:
# Random
import numpy as np

print("1D")
arr1 = np.random.rand(3)
print(arr1)

print("2D")
arr2 = np.random.rand(2,5)
print(arr2)

print("3D")
arr3 = np.random.rand(2,5,1)
print(arr3)

print("5D")
arr5 = np.random.rand(2,3,2,2,3)
print(arr5)


1D
[0.15320539 0.64237949 0.41908005]
2D
[[0.40948932 0.80914366 0.44588447 0.75615811 0.82226989]
 [0.0135887  0.0606429  0.78208154 0.80740818 0.03031652]]
3D
[[[0.18395492]
  [0.45192289]
  [0.63005314]
  [0.18986529]
  [0.33979612]]

 [[0.6899706 ]
  [0.10855048]
  [0.63744078]
  [0.64659479]
  [0.27566748]]]
5D
[[[[[3.29388051e-01 3.35619424e-01 1.37185039e-01]
    [2.56961518e-01 8.37041674e-01 3.99425781e-01]]

   [[3.85127822e-01 4.51033715e-01 8.84006725e-01]
    [6.17465033e-01 8.22639585e-01 6.87943335e-02]]]


  [[[1.90951940e-01 4.98194441e-01 2.41679631e-01]
    [6.65607692e-01 3.64336847e-01 4.86201857e-01]]

   [[7.11223731e-01 8.05014177e-01 5.53319011e-01]
    [7.45671135e-01 8.72339059e-01 2.23523143e-01]]]


  [[[7.14989537e-01 1.16382577e-01 2.63556031e-01]
    [9.97529267e-01 4.29179982e-01 4.57551863e-01]]

   [[9.33045795e-02 3.11878470e-01 3.14667544e-01]
    [3.95493335e-01 3.73307632e-01 5.50179687e-01]]]]



 [[[[8.28099294e-01 5.88434567e-01 8.01067524e-01]

In [39]:
x = np.arange(0, 9) 
print (x)
print (type(x))

[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [41]:
A = np.array([x, np.ones(9)]) 
print(A)

[[0. 1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
